### PR TITLE
Update SynScan example to current INDI API, and other improvements

### PR DESCRIPTION
**Pull request by nybble41**
I needed a bridge between Ekos and the Stellarium Mobile Plus Android app and the SynScan example here seemed like a perfect fit, but I had some trouble getting it working at first. It seems that the type names had changed, and the former `.s` attribute had been replaced with `getState()` and `setState()` member functions. The example also tended to get stuck in unbounded loops when it couldn't read a property, for example because the type of object returned by `getSwitch()` or `getNumber()` didn't match expectations, or because a particular property was not implemented. Some loops had retry limits but most did not.

I fixed the issues noted above and also cleaned up some of the (IMHO) more awkward and repetitive code. With these changes I can connect to INDI and accept connections from Stellarium, synchronizing time, location, and telescope tracking data. The SYNC and GOTO commands and manual mount controls also work as expected. There are still rough edges (one must edit the script to change the telescope name, for example) and I am not certain Stellarium exercises all the SynScan commands implemented here, but the parts I have seen appear fully functional.

Tested with libindi-dev 1.9.4+dfsg-1 and Python 3.10.4 on Debian Sid, and Stellarium Mobile Plus v1.8.8.

### CODE REVIEW

**Comment by knro** [comment]
Super! Do you think we need to update any of the documentation so that prospective developers can start faster on their pyindi-projects in the future?

**Comment by nybble41** [comment]
The issues I encountered were related (I think) to changes in the underlying INDI libraries, so the C++ API documentation should suffice. I did notice that there are some minor issues with the example in README.md, and a missing SWIG wrapper for INDI::Properties which causes iteration over the object returned by `d.getProperties()` to fail. I have the necessary changes in my [readme-example](https://github.com/nybble41/pyindi-client/tree/readme-example) branch and will submit these changes in a separate pull request.

The other example clients may need similar updates.

**Comment by artak-kirakosyan** [comment]
@knro I am unable to dedicate time to this project, so please remove me from the review list and also share the access with someone else in pypy.org so that they can organize releases if needed.

**Comment by knro** [comment]
Sure @artak-kirakosyan . @abecadel Are you willing to help maintaining this project and managing Pypy releases?

**Comment by abecadel** [comment]
@knro sure, will be happy to help

**Pull request merged**
